In [1]:
# It describes patient medical record data for Pima Indians and whether they had an onset of diabetes within five years

In [1]:
# It is a binary classification problem (onset of diabetes as 1 or not as 0)
#  All the input variables that describe each patient are transformed and numerical.

In [2]:
#  The steps you will learn in this

#(1) How to load data
#(2) How to define a neural network in PyTorch
#(3)  How to train a model on data
#(4)  How to evaluate a model
#(5)  How to make predictions with the model

In [1]:
#The  required library are listed below:

import torch as th
import torch.optim as op
import torch.nn as nn

In [2]:
# numpy base library
import numpy as np

In [3]:
# pands base library
import pandas as pd

In [4]:
# extracting the data 

dt=np.loadtxt("pima-indians-diabetes.data.csv",delimiter=",")
dt

# load the dataset, split into input (X) and output (y) variables

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [7]:
x=dt[:,0:8] #  “:“. You can select the first eight columns from index 0 to index 7 via the slice 0:8.

y=dt[:,8] # You can then select the output column (the 9th variable) via index 8.

In [8]:
x,y

(array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
        [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
        [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
        ...,
        [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
        [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
        [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]]),
 array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
        0., 1., 0., 0., 0., 1., 1., 0.,

In [75]:
# shape of the x before tranforming to tensor
x.shape

(768, 8)

In [162]:
#To convert, create a tensor out of NumPy arrays:

X=th.FloatTensor(x)
Y=th.FloatTensor(y.reshape(-1,1))

In [163]:
X,Y

(tensor([[  6.0000, 148.0000,  72.0000,  ...,  33.6000,   0.6270,  50.0000],
         [  1.0000,  85.0000,  66.0000,  ...,  26.6000,   0.3510,  31.0000],
         [  8.0000, 183.0000,  64.0000,  ...,  23.3000,   0.6720,  32.0000],
         ...,
         [  5.0000, 121.0000,  72.0000,  ...,  26.2000,   0.2450,  30.0000],
         [  1.0000, 126.0000,  60.0000,  ...,  30.1000,   0.3490,  47.0000],
         [  1.0000,  93.0000,  70.0000,  ...,  30.4000,   0.3150,  23.0000]]),
 tensor([[1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [0.],
         [0.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [0.

In [142]:
X.shape # shape of the x after tranfroming into to tensor

torch.Size([768, 8])

In [143]:
# define the model

In [170]:
mdl=nn.Sequential(
    nn.Linear(8,10),
    nn.ReLU(),
    nn.Linear(10,6),
    nn.ReLU(),
    nn.Linear(6,1),
    nn.Sigmoid()
)

In [171]:
mdl

Sequential(
  (0): Linear(in_features=8, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=6, bias=True)
  (3): ReLU()
  (4): Linear(in_features=6, out_features=1, bias=True)
  (5): Sigmoid()
)

In [172]:
class LinearRgression(nn.Module):
    def __init__(self):          #  __init__ sets up the network's structure by defining the layers
        super(). __init__()
        
        self.hidden1 = nn.Linear(8, 12)
        self.act1 = nn.ReLU()
        self.hidden2 = nn.Linear(12, 8)
        self.act2 = nn.ReLU()
        self.output = nn.Linear(8, 1)
        self.act_output = nn.Sigmoid()
        
        def forward(self,x):   #  while forward specifies how the data flows through the network
        x = self.act1(self.hidden1(x))
        x = self.act2(self.hidden2(x))
        x = self.act_output(self.output(x))
        return x

model=LinearRgression()
print(model)

LinearRgression(
  (hidden1): Linear(in_features=8, out_features=10, bias=True)
  (act1): ReLU()
  (hidden2): Linear(in_features=10, out_features=6, bias=True)
  (act2): ReLU()
  (output): Linear(in_features=6, out_features=1, bias=True)
)


In [173]:
# Preparation for Training

#  Adam is used. This popular version of gradient descent can automatically tune 
#  itself and gives good results in a wide range of problems.

In [174]:
crietrion=nn.BCELoss() #  beacuse it's binary classification problem so we used BCELoss
optimizer=op.Adam(mdl.parameters(),lr=0.01) 

In [149]:
# The goal of training a model is to ensure it learns a good enough mapping of input data to output classification.

In [208]:
#The simplest way to build a training loop is to use two nested for-loops, one for epochs and one for batches:

n_epochs=10 # Epoch: Passes the entire training dataset to the model once
batch_size=5 # Batch: breaking the largedata into batchs

for epoch in range(n_epochs):
    for k in range(0,len(X),(batch_size)):
        
        Xbatch=X[k:k+batch_size]
        Ybatch=Y[k:k+batch_size]
        
        YP=mdl(Xbatch)
        loss=crietrion(YP,Ybatch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        print(f"finshed epoch {epoch},latest loss {loss}")

finshed epoch 0,latest loss 0.09255659580230713
finshed epoch 0,latest loss 1.0686887502670288
finshed epoch 0,latest loss 0.30502453446388245
finshed epoch 0,latest loss 1.3588203191757202
finshed epoch 0,latest loss 0.5143686532974243
finshed epoch 0,latest loss 0.2316938191652298
finshed epoch 0,latest loss 0.3833681046962738
finshed epoch 0,latest loss 0.8236112594604492
finshed epoch 0,latest loss 1.3301305770874023
finshed epoch 0,latest loss 0.4229448437690735
finshed epoch 0,latest loss 0.5627096891403198
finshed epoch 0,latest loss 0.5723547339439392
finshed epoch 0,latest loss 0.41112813353538513
finshed epoch 0,latest loss 0.5617367625236511
finshed epoch 0,latest loss 0.5861992835998535
finshed epoch 0,latest loss 0.12578782439231873
finshed epoch 0,latest loss 0.34898841381073
finshed epoch 0,latest loss 0.20775166153907776
finshed epoch 0,latest loss 0.5895050168037415
finshed epoch 0,latest loss 0.49416083097457886
finshed epoch 0,latest loss 0.2346194088459015
finshed e

finshed epoch 1,latest loss 0.7309952974319458
finshed epoch 1,latest loss 0.5172201991081238
finshed epoch 1,latest loss 0.1275176703929901
finshed epoch 1,latest loss 1.1001030206680298
finshed epoch 1,latest loss 0.6593838930130005
finshed epoch 1,latest loss 0.10518918931484222
finshed epoch 1,latest loss 1.233642816543579
finshed epoch 1,latest loss 0.2994978129863739
finshed epoch 1,latest loss 0.11829545348882675
finshed epoch 1,latest loss 0.4695255160331726
finshed epoch 1,latest loss 0.7475336194038391
finshed epoch 1,latest loss 0.30875474214553833
finshed epoch 1,latest loss 0.7492386102676392
finshed epoch 1,latest loss 0.6058359146118164
finshed epoch 1,latest loss 0.33814722299575806
finshed epoch 1,latest loss 0.23301896452903748
finshed epoch 1,latest loss 0.42783108353614807
finshed epoch 1,latest loss 0.7851254343986511
finshed epoch 1,latest loss 0.5687569379806519
finshed epoch 1,latest loss 0.8558191061019897
finshed epoch 1,latest loss 0.8429935574531555
finshed 

finshed epoch 2,latest loss 0.2650561034679413
finshed epoch 2,latest loss 0.25589650869369507
finshed epoch 2,latest loss 0.6127901077270508
finshed epoch 2,latest loss 0.28722816705703735
finshed epoch 2,latest loss 0.5456668734550476
finshed epoch 2,latest loss 0.5815987586975098
finshed epoch 2,latest loss 0.26512566208839417
finshed epoch 2,latest loss 0.1084960550069809
finshed epoch 2,latest loss 0.13315793871879578
finshed epoch 2,latest loss 0.5775390863418579
finshed epoch 2,latest loss 1.2505186796188354
finshed epoch 2,latest loss 0.45648646354675293
finshed epoch 2,latest loss 0.10387597978115082
finshed epoch 2,latest loss 0.19095270335674286
finshed epoch 2,latest loss 0.43818649649620056
finshed epoch 2,latest loss 0.5266939997673035
finshed epoch 2,latest loss 0.11111825704574585
finshed epoch 2,latest loss 0.5395453572273254
finshed epoch 2,latest loss 0.7282892465591431
finshed epoch 2,latest loss 0.29135340452194214
finshed epoch 2,latest loss 0.4541531205177307
fin

finshed epoch 3,latest loss 0.29461827874183655
finshed epoch 3,latest loss 0.36722657084465027
finshed epoch 3,latest loss 0.30608972907066345
finshed epoch 3,latest loss 0.2340594232082367
finshed epoch 3,latest loss 0.8853504061698914
finshed epoch 3,latest loss 0.3806320130825043
finshed epoch 3,latest loss 0.6313742995262146
finshed epoch 3,latest loss 0.3775651454925537
finshed epoch 3,latest loss 0.43585309386253357
finshed epoch 3,latest loss 0.4418681561946869
finshed epoch 3,latest loss 0.17765553295612335
finshed epoch 3,latest loss 0.27357038855552673
finshed epoch 4,latest loss 0.09343203902244568
finshed epoch 4,latest loss 1.059821605682373
finshed epoch 4,latest loss 0.3072049021720886
finshed epoch 4,latest loss 1.358014464378357
finshed epoch 4,latest loss 0.5110878348350525
finshed epoch 4,latest loss 0.22715315222740173
finshed epoch 4,latest loss 0.38369643688201904
finshed epoch 4,latest loss 0.7886085510253906
finshed epoch 4,latest loss 1.3298087120056152
finshe

finshed epoch 5,latest loss 0.5504022240638733
finshed epoch 5,latest loss 0.4992494583129883
finshed epoch 5,latest loss 0.60856693983078
finshed epoch 5,latest loss 0.6464210748672485
finshed epoch 5,latest loss 0.23802609741687775
finshed epoch 5,latest loss 0.7463226914405823
finshed epoch 5,latest loss 0.456664502620697
finshed epoch 5,latest loss 0.7282898426055908
finshed epoch 5,latest loss 0.5017396211624146
finshed epoch 5,latest loss 0.1277693212032318
finshed epoch 5,latest loss 1.1100380420684814
finshed epoch 5,latest loss 0.6541270017623901
finshed epoch 5,latest loss 0.12985359132289886
finshed epoch 5,latest loss 1.2535414695739746
finshed epoch 5,latest loss 0.29985398054122925
finshed epoch 5,latest loss 0.11095897853374481
finshed epoch 5,latest loss 0.4706185460090637
finshed epoch 5,latest loss 0.7704099416732788
finshed epoch 5,latest loss 0.5915059447288513
finshed epoch 5,latest loss 0.7521580457687378
finshed epoch 5,latest loss 0.5799959897994995
finshed epoc

finshed epoch 6,latest loss 0.42761659622192383
finshed epoch 6,latest loss 0.7853342890739441
finshed epoch 6,latest loss 0.5676987767219543
finshed epoch 6,latest loss 0.8485742807388306
finshed epoch 6,latest loss 0.8391380310058594
finshed epoch 6,latest loss 0.6588420867919922
finshed epoch 6,latest loss 0.7975701093673706
finshed epoch 6,latest loss 0.5188657641410828
finshed epoch 6,latest loss 0.27183640003204346
finshed epoch 6,latest loss 0.7912636995315552
finshed epoch 6,latest loss 1.160045862197876
finshed epoch 6,latest loss 0.1505676954984665
finshed epoch 6,latest loss 0.45375877618789673
finshed epoch 6,latest loss 0.20996153354644775
finshed epoch 6,latest loss 1.0568649768829346
finshed epoch 6,latest loss 0.2812315821647644
finshed epoch 6,latest loss 0.19391471147537231
finshed epoch 6,latest loss 0.49589091539382935
finshed epoch 6,latest loss 0.5633633732795715
finshed epoch 6,latest loss 0.35092824697494507
finshed epoch 6,latest loss 0.18651095032691956
finshe

finshed epoch 7,latest loss 0.11029312759637833
finshed epoch 7,latest loss 0.1357807219028473
finshed epoch 7,latest loss 0.5751442313194275
finshed epoch 7,latest loss 1.239841341972351
finshed epoch 7,latest loss 0.4571259021759033
finshed epoch 7,latest loss 0.10564754903316498
finshed epoch 7,latest loss 0.19079700112342834
finshed epoch 7,latest loss 0.47359761595726013
finshed epoch 7,latest loss 0.5232730507850647
finshed epoch 7,latest loss 0.11318759620189667
finshed epoch 7,latest loss 0.539455771446228
finshed epoch 7,latest loss 0.7231389880180359
finshed epoch 7,latest loss 0.2984481155872345
finshed epoch 7,latest loss 0.4623776078224182
finshed epoch 7,latest loss 0.4210927486419678
finshed epoch 7,latest loss 0.254311740398407
finshed epoch 7,latest loss 0.27603811025619507
finshed epoch 7,latest loss 0.2507138252258301
finshed epoch 7,latest loss 0.5275380611419678
finshed epoch 7,latest loss 0.7407813668251038
finshed epoch 7,latest loss 0.2907111942768097
finshed ep

finshed epoch 8,latest loss 0.3761438727378845
finshed epoch 8,latest loss 0.43660813570022583
finshed epoch 8,latest loss 0.4420545697212219
finshed epoch 8,latest loss 0.17900994420051575
finshed epoch 8,latest loss 0.27294814586639404
finshed epoch 9,latest loss 0.09304064512252808
finshed epoch 9,latest loss 1.0522311925888062
finshed epoch 9,latest loss 0.3087526559829712
finshed epoch 9,latest loss 1.3554613590240479
finshed epoch 9,latest loss 0.5098720788955688
finshed epoch 9,latest loss 0.2228473722934723
finshed epoch 9,latest loss 0.38595542311668396
finshed epoch 9,latest loss 0.7838743925094604
finshed epoch 9,latest loss 1.3376210927963257
finshed epoch 9,latest loss 0.4238778054714203
finshed epoch 9,latest loss 0.5596043467521667
finshed epoch 9,latest loss 0.5731254816055298
finshed epoch 9,latest loss 0.41415542364120483
finshed epoch 9,latest loss 0.5596763491630554
finshed epoch 9,latest loss 0.5884457230567932
finshed epoch 9,latest loss 0.12688857316970825
finshe

In [227]:
# Evaluate the Model
    
y_pred=mdl(X)
Accuracy=(y_pred.round() == Y).float().mean()
print(f" accuracy {accuracy}")

 accuracy 0.78515625


In [232]:
# make probability predictions with the model
predictions = mdl(X)
# round predictions
rounded = predictions.round()

In [236]:
# make class predictions with the model
predictions = (mdl(X) > 0.5).int()
for i in range(5):
    print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))

[6.0, 148.0, 72.0, 35.0, 0.0, 33.599998474121094, 0.6269999742507935, 50.0] => 1 (expected 1)
[1.0, 85.0, 66.0, 29.0, 0.0, 26.600000381469727, 0.35100001096725464, 31.0] => 0 (expected 0)
[8.0, 183.0, 64.0, 0.0, 0.0, 23.299999237060547, 0.671999990940094, 32.0] => 1 (expected 1)
[1.0, 89.0, 66.0, 23.0, 94.0, 28.100000381469727, 0.16699999570846558, 21.0] => 0 (expected 0)
[0.0, 137.0, 40.0, 35.0, 168.0, 43.099998474121094, 2.2880001068115234, 33.0] => 1 (expected 1)
